### ISSUE TITLE
Able to register and log in with Google or Github providers

### ISSUE THREAD

**Issue by aymericaitamer** [platform-as-code/roadmap#1]
# Value proposition
**As a** developer (new user)
**I want to** register & log in to the platform
**So, I can** use it

# Description & Recommendations
It's very straightforward : Users need to register and log in to our platform to use it. 
We need to focus our energy on our core product so we will use a third party to manage authentification : [Auth0](https://auth0.com/).

# Tasks
- [X] Create Auth0 tenant.
- [ ] Setup Auth0 tenant (settings, design, domains...). 
- [ ] Enable and configure only Google and Github social logins.
- [ ] Manage session in the web console (redirect after log in/registration, being logged and be able to log out)

# Questions
- Login page domain and design?
- Time session and cookies (security)?
- User ID and database?
- Stripe?

# Acceptance criteria & Error handling
- [ ] **When** I go to login URL, **then** I see a login page with only Google or Github buttons.
- [ ] **When** I click on Google or Github buttons, **then** system ask me to log in using the corresponding provider.
- [ ] **When** I'm logged, **then** system redirect me to web console and connect me.
- [ ] **When** I use wrong credentials, **then** system display default error messages from providers or auth0.
