### ISSUE TITLE
Generate a GIT repository and SSH keys after registration to test our platform securely (mynamespace/try.git)

### ISSUE THREAD

**Issue by aymericaitamer** [platform-as-code/roadmap#2]
# Value proposition
**As a** developer (new user)
**I want to** have a git repository and SSH keys
**So, I can** test the platform securely

# Description & Recommendations
This is the core of our product, so we need to think and work smart. We need create a strong API and make our first 3 integrations (auth0,, git server and frontend) in order to fulfil the value proposition. The registration and API processes should be very fast because it would be the first loading for our new users.

# Tasks
- [ ] Create PaC API (domain, routes, API accesses, ...)
- [ ] Create first endpoint(s) to : Create namespace, create bare git repository "try.git" and generate SSH keys to install on git server.
- [ ] Create second endpoint(s) to : Display all informations above (for frontend).
- [ ] PaC API and Auth0 integration : After registration Auth0 calls our API endpoint(s).
- [ ] PaC API and PaC Git server integration : Create bare repository try.git, generate SSH keys and install it with gitolite.
- [ ] PaC API and PaC frontend : Simple GET endpoints to display informations.

# Questions
- API domain and access ?
- Communication with git server (git commit/push), frontend (request module) and auth0 (webhook) ?
- Use only auth0 and git Server databases or create our own (mysql) ?
- No frontend endpoints and send email instead ?

# Acceptance criteria & Error handling
- [ ] **When** I complete the registration process, **then** Auth0 should call our API to create namespace, git repository and SSH keys and then redirect to the web console.
- [ ]  **When** Our API endpoint is called, **then** a git repository is created and I can push on it using the SSH keys generated.
- [ ] **Given** I'm logged on frontend web console **When** I load the homepage "/", **then** the front should call our API and display the right information for the logged user.
